In [1]:
import numpy as np

## First we are building a simple network which contain no hidden layer.

In [2]:
# Taking AND gate as example
X = np.array([[0,0],[0,1],[1,0],[1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape,Y.shape

((4, 2), (4, 1))

In [3]:
# Useing sigmoid function as activation function.
def sig(z):
    return 1/(1 + np.exp(-z))

In [15]:
# Derivative of sigmoid function
def derivativeSig(z):
    return sig(z) * (1 - sig(z))

In [21]:
# Initialize weights and bias
# We should initialize them in range (-1,1)
weights = 2*np.random.random((2,1)) - 1 # Corresponding to two features
bias = 2*np.random.random(1) - 1 # Since a single output unit only 1 bias is required
print(weights)
print(bias)

[[0.74303209]
 [0.50621246]]
[0.38930704]


In [7]:
output0 = X # It is output from input layer and this goes in following layer
output = sig(np.dot(output0,weights) + bias)
output
# So this is output corresponding to current weights 

array([[0.27823769],
       [0.49568968],
       [0.14528405],
       [0.3023568 ]])

## Now we will construct network for one hidden layer containing two units

In [8]:
# We will use same data and only number of features and bias will change
# For hidden layer
wh = 2*np.random.random((2,2)) - 1
bh = 2*np.random.random((1,2)) - 1
# For output layer
wo = 2*np.random.random((2,1)) - 1
bo = 2*np.random.random((1,1)) - 1

In [10]:
output0 = X # It is output from input layer and this goes in following layer
output_hidden = sig(np.dot(output0,wh) + bh)
output = sig(np.dot(output_hidden,wo) + bo)
output
# So this is output corresponding to current weights with one hidden layer

array([[0.40968374],
       [0.40475565],
       [0.4063181 ],
       [0.4006677 ]])

## Now Backpropogation on network with no hidden layer

In [20]:
lr = 0.1 #learning rate
for iter in range(10000):
    output0 = X 
    output = sig(np.dot(output0,weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0,weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term

    wt_changes = np.array([[0.0],[0.0]])
    bias_change = 0.0

    for i in range(2):
        for j in range(4):
            wt_changes[i][0] += first_two[j][0] * output0[j][i]
        
    for j in range(4):
        bias_change += first_two[j][0] * 1
    
    weights = weights - lr * wt_changes
    bias = bias - lr * bias_change

output = sig(np.dot(X,weights) + bias)
print(weights)
print(bias)
print(output)

[[5.60298672]
 [5.60298674]]
[-8.49664105]
[[2.04111288e-04]
 [5.24681464e-02]
 [5.24681451e-02]
 [9.37575087e-01]]


In [22]:
# We can do above thing in shorter way
lr = 0.1 #learning rate
for iter in range(10000):
    output0 = X 
    output = sig(np.dot(output0,weights) + bias)

    first_term = output - Y
    input_for_last_layer = np.dot(output0,weights) + bias
    second_term = derivativeSig(input_for_last_layer)
    first_two = first_term * second_term

    wt_changes = np.dot(output0.T,first_two)
    bias_change = np.sum(first_two)
    weights = weights - lr * wt_changes
    bias = bias - lr * bias_change

output = sig(np.dot(X,weights) + bias)
print(weights)
print(bias)
print(output)

[[5.47955292]
 [5.47955291]]
[-8.31202093]
[[2.45487030e-04]
 [5.55946754e-02]
 [5.55946757e-02]
 [9.33831093e-01]]


## So our output is similar to actual Y values in both cases